# Site settings
description: A blog from the Ritter Insurance Marketing Software development department, a.k.a. RIMdev
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://rimdev.io
enforce_ssl: rimdev.io
rim_copy: Ritter Insurance Marketing LLC
rim_url: https://ritterim.com
rim_blog: https://blog.ritterim.com
map_url: https://www.google.com/maps/place/2600+Commerce+Dr,+Harrisburg,+PA+17110/@40.311295,-76.843902,14z/data=!4m2!3m1!1s0x89c8c76c07f542d5:0xa2d30cdf7911f0fa?hl=en
default_image: /images/default/rimdev-surface.jpg
safe: false
title: RIMdev Technical Blog

# Font Awesome version
fa_version: 4.6.0

# Build settings
timezone: America/New_York
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
# sitemap: false in front matter of page to exclude
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# will convert @twitter-handle to the full twitter link in a post
jekyll-mentions: https://twitter.com

# User settings
username: RIMdev
user_description: Ritter Insurance Marketing | Software DEVelopment
user_title: RIMdev
user_logo: /assets/img/logos/RIMdev-logo-text-white.svg
user_icon: /assets/img/logos/RIMdev-icon-white.svg
email: anon@ritterim.com
twitter_username: ritterim
github_username:  ritterim
disqus_username: rimdev

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules/@angular', 'node_modules/core-js', 'node_modules/lodash.uniq', 'node_modules/ng2-cookies', 'node_modules/rxjs', 'node_modules/symbol-observable', 'node_modules/ts-helpers', 'node_modules/uuid', 'node_modules/zone.js']

# Url Shortener
shortener:
  basepath: /s/        # Path for stored redirects.
  preserve: false      # Keep previously generated files.
  salt:     "RimDev"   # The optional salt, used when hasing the Unix time.

# RIMdev posting authors
RIMdev:
  Khalid Abuhakmeh:
    avatar: https://avatars0.githubusercontent.com/u/228256?v=3
    title: Director of Software Development
    desc: Focused on ASP.NET and Microsoft. Still love OSS &amp; Startups.
    twitter: buhakmeh
    github: khalidabuhakmeh
  Bill Boga:
    avatar: https://avatars2.githubusercontent.com/u/3382469?v=3
    title: Senior Software Developer
    desc: Polyglot with focus on C#. Also enjoy building and tinkering with hardware.
    twitter: billbogaiv
    github: billbogaiv
  Ken Dale:
    avatar: https://avatars3.githubusercontent.com/u/1012917?v=3
    title: Senior Application Developer
    twitter: kendaleiv
    github: kendaleiv
  Ken Earl:
    avatar: https://avatars0.githubusercontent.com/u/1807843?v=3
    github: McKenjo
  Tim Graham:
    avatar: https://avatars3.githubusercontent.com/u/7881414?v=3
    twitter:
    github: TimGIMT
  Tom Harold:
    avatar: https://avatars3.githubusercontent.com/u/4880437?v=3
    github: tgharold
  Scott Henscheid:
    avatar: https://avatars3.githubusercontent.com/u/10855826?v=3
    github: scotthenscheid
  Kevin Hougasian:
    avatar: https://avatars2.githubusercontent.com/u/6231956?v=3
    title: Senior Frontend Developer
    desc:
    twitter: hougasian
    github: hougasian
  Justin Rusbatch:
    avatar: https://avatars0.githubusercontent.com/u/423549?v=3
    twitter: jrusbatch
    github: jrusbatch
  Chad Peters:
    avatar: https://avatars3.githubusercontent.com/u/2921868?v=3
    github: lightyeare
  Scott Schwalm:
    avatar: https://avatars0.githubusercontent.com/u/3587144?v=3
    github: ScottSchwalm
  Beth Warner:
    avatar: https://avatars2.githubusercontent.com/u/1625929?v=3
    github: bwarner22
  Nathan White:
    avatar: https://avatars1.githubusercontent.com/u/4616177?v=3
    title: Frontend Developer
    desc:
    twitter: comfroels
    github: comfroels

ritter_links:
  - service: Ritter Insurance Marketing
    url: https://www.ritterim.com
  - service: Insurance Insider News by Craig Ritter
    url: https://blog.ritterim.com
  - service: Ritter Agent News
    url: https://www.ritterim.com/agentnews
  - service: Medicareful.com
    url: https://medicareful.com
  - service: eBroker Software
    url: https://ebrokersoftware.com
